# Netlify configuration for NFT Marketplace Frontend
[build]
  # Build command
  command = "pnpm run build"
  
  # Output directory
  publish = ".next"

# Environment variables for production
[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Backend API URL
  NEXT_PUBLIC_API_URL = "https://nft-market-api.netlify.app/api"
  
  # Blockchain Configuration
  NEXT_PUBLIC_CONTRACT_ADDRESS = "0x5B8c37aBdd3Dc72874d20a9403549798309599b5"
  NEXT_PUBLIC_CHAIN_ID = "80002"
  NEXT_PUBLIC_NETWORK_NAME = "Polygon Amoy"
  NEXT_PUBLIC_RPC_URL = "https://rpc-amoy.polygon.technology/"
  NEXT_PUBLIC_BLOCK_EXPLORER = "https://amoy.polygonscan.com/"
  
  # IPFS Configuration
  NEXT_PUBLIC_IPFS_GATEWAY = "https://gateway.pinata.cloud/ipfs/"
  
  # Firebase Configuration (update with your values)
  NEXT_PUBLIC_FIREBASE_API_KEY = "your_firebase_api_key"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "your-project-id"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "123456789012"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:123456789012:web:abcdefghijklmnopqr"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Functions for Netlify Edge (optional)
[functions]
  directory = "netlify/functions"
